/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author Karen.Vargas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenu = new javax.swing.JLabel();
        jLabelMenu1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        administrarBoton = new javax.swing.JButton();
        buscarBoton = new javax.swing.JButton();
        prestarBoton = new javax.swing.JButton();
        jLabelMenu2 = new javax.swing.JLabel();
        jLabelMenu3 = new javax.swing.JLabel();
        jLabelMenu4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 300));
        getContentPane().setLayout(null);

        jLabelMenu.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(102, 102, 102));
        jLabelMenu.setText("Biblioteca Virtual");
        getContentPane().add(jLabelMenu);
        jLabelMenu.setBounds(230, 40, 240, 60);

        jLabelMenu1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelMenu1.setForeground(new java.awt.Color(255, 102, 102));
        jLabelMenu1.setText("Prestamos");
        getContentPane().add(jLabelMenu1);
        jLabelMenu1.setBounds(430, 240, 150, 60);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(200, 50, 200, 10);

        administrarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/1_1.png"))); // NOI18N
        administrarBoton.setToolTipText("");
        administrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(administrarBoton);
        administrarBoton.setBounds(50, 110, 140, 130);

        buscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/2_1.png"))); // NOI18N
        getContentPane().add(buscarBoton);
        buscarBoton.setBounds(230, 110, 150, 130);

        prestarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/img/3_1.png"))); // NOI18N
        getContentPane().add(prestarBoton);
        prestarBoton.setBounds(420, 110, 150, 130);

        jLabelMenu2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabelMenu2.setForeground(new java.awt.Color(255, 102, 102));
        jLabelMenu2.setText("Bienvenido");
        getContentPane().add(jLabelMenu2);
        jLabelMenu2.setBounds(200, -10, 220, 70);

        jLabelMenu3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelMenu3.setForeground(new java.awt.Color(255, 102, 102));
        jLabelMenu3.setText("Administra");
        getContentPane().add(jLabelMenu3);
        jLabelMenu3.setBounds(50, 240, 150, 60);

        jLabelMenu4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelMenu4.setForeground(new java.awt.Color(255, 102, 102));
        jLabelMenu4.setText("Busca");
        getContentPane().add(jLabelMenu4);
        jLabelMenu4.setBounds(270, 240, 150, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void administrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_administrarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administrarBoton;
    private javax.swing.JButton buscarBoton;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMenu1;
    private javax.swing.JLabel jLabelMenu2;
    private javax.swing.JLabel jLabelMenu3;
    private javax.swing.JLabel jLabelMenu4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton prestarBoton;
    // End of variables declaration//GEN-END:variables
}
